[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true     #allow foundry to run commands directly on the machine

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
